// src/main/webapp/app/account/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';

import SharedModule from 'app/shared/shared.module';
import { AccountService } from 'app/core/auth/account.service';
import { Account } from 'app/core/auth/account.model';
import { LANGUAGES } from 'app/config/language.constants';

const initialAccount: Account = {} as Account;

@Component({
  selector: 'mmse-settings',
  standalone: true,
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
  templateUrl: './settings.component.html',
})
export default class SettingsComponent implements OnInit {
  success = false;
  languages = LANGUAGES;

  settingsForm = new FormGroup({
    firstName: new FormControl(initialAccount.firstName, {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(1), Validators.maxLength(50)],
    }),
    lastName: new FormControl(initialAccount.lastName, {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(1), Validators.maxLength(50)],
    }),
    email: new FormControl(initialAccount.email, {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(5), Validators.maxLength(254), Validators.email],
    }),
    langKey: new FormControl(initialAccount.langKey, { nonNullable: true }),

    activated: new FormControl(initialAccount.activated, { nonNullable: true }),
    authorities: new FormControl(initialAccount.authorities, { nonNullable: true }),
    imageUrl: new FormControl(initialAccount.imageUrl, { nonNullable: true }),
    login: new FormControl(initialAccount.login, { nonNullable: true }),
  });

  constructor(private accountService: AccountService, private translateService: TranslateService) {}

  ngOnInit(): void {
    this.accountService.identity().subscribe(account => {
      if (account) {
        this.settingsForm.patchValue(account);
      }
    });
  }

  save(): void {
    this.success = false;

    const account = this.settingsForm.getRawValue();
    this.accountService.save(account).subscribe(() => {
      this.success = true;

      this.accountService.authenticate(account);

      if (account.langKey !== this.translateService.currentLang) {
        this.translateService.use(account.langKey);
      }
    });
  }
}

<div>
  <div class="d-flex justify-content-center">
    <div class="col-md-8">
      <h2 mmseTranslate="settings.title" [translateValues]="{ username: settingsForm.value.login }" *ngIf="settingsForm.value.login">
        User settings for [<strong>{{ settingsForm.value.login }}</strong
        >]
      </h2>

      <div class="alert alert-success" *ngIf="success" mmseTranslate="settings.messages.success">
        <strong>Settings saved!</strong>
      </div>

      <mmse-alert-error></mmse-alert-error>

      <form name="form" role="form" (ngSubmit)="save()" [formGroup]="settingsForm" *ngIf="settingsForm.value.login" novalidate>
        <div class="mb-3">
          <label class="form-label" for="firstName" mmseTranslate="settings.form.firstname">First Name</label>
          <input
            type="text"
            class="form-control"
            id="firstName"
            name="firstName"
            placeholder="{{ 'settings.form.firstname.placeholder' | translate }}"
            formControlName="firstName"
            data-cy="firstname"
          />

          <div
            *ngIf="
              settingsForm.get('firstName')!.invalid && (settingsForm.get('firstName')!.dirty || settingsForm.get('firstName')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('firstName')?.errors?.required"
              mmseTranslate="settings.messages.validate.firstname.required"
            >
              Your first name is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('firstName')?.errors?.minlength"
              mmseTranslate="settings.messages.validate.firstname.minlength"
            >
              Your first name is required to be at least 1 character
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('firstName')?.errors?.maxlength"
              mmseTranslate="settings.messages.validate.firstname.maxlength"
            >
              Your first name cannot be longer than 50 characters
            </small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" for="lastName" mmseTranslate="settings.form.lastname">Last Name</label>
          <input
            type="text"
            class="form-control"
            id="lastName"
            name="lastName"
            placeholder="{{ 'settings.form.lastname.placeholder' | translate }}"
            formControlName="lastName"
            data-cy="lastname"
          />

          <div
            *ngIf="settingsForm.get('lastName')!.invalid && (settingsForm.get('lastName')!.dirty || settingsForm.get('lastName')!.touched)"
          >
            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('lastName')?.errors?.required"
              mmseTranslate="settings.messages.validate.lastname.required"
            >
              Your last name is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('lastName')?.errors?.minlength"
              mmseTranslate="settings.messages.validate.lastname.minlength"
            >
              Your last name is required to be at least 1 character
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('lastName')?.errors?.maxlength"
              mmseTranslate="settings.messages.validate.lastname.maxlength"
            >
              Your last name cannot be longer than 50 characters
            </small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" for="email" mmseTranslate="global.form.email.label">Email</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="{{ 'global.form.email.placeholder' | translate }}"
            formControlName="email"
            data-cy="email"
          />

          <div *ngIf="settingsForm.get('email')!.invalid && (settingsForm.get('email')!.dirty || settingsForm.get('email')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('email')?.errors?.required"
              mmseTranslate="global.messages.validate.email.required"
            >
              Your email is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('email')?.errors?.email"
              mmseTranslate="global.messages.validate.email.invalid"
            >
              Your email is invalid.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('email')?.errors?.minlength"
              mmseTranslate="global.messages.validate.email.minlength"
            >
              Your email is required to be at least 5 characters.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="settingsForm.get('email')?.errors?.maxlength"
              mmseTranslate="global.messages.validate.email.maxlength"
            >
              Your email cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="mb-3" *ngIf="languages && languages.length > 0">
          <label for="langKey" mmseTranslate="settings.form.language">Language</label>
          <select class="form-control" id="langKey" name="langKey" formControlName="langKey" data-cy="langKey">
            <option *ngFor="let language of languages" [value]="language">{{ language | findLanguageFromKey }}</option>
          </select>
        </div>

        <button
          type="submit"
          [disabled]="settingsForm.invalid"
          class="btn btn-primary"
          mmseTranslate="settings.form.button"
          data-cy="submit"
        >
          Save
        </button>
      </form>
    </div>
  </div>
</div>

// src/main/webapp/app/account/settings/settings.vue
<template>
  <div>
    <div class="row justify-content-center">
      <div class="col-md-8 toastify-container">
        <h2 v-if="username" id="settings-title">
          <span v-html="t$('settings.title', { username: username })"></span>
        </h2>

        <div class="alert alert-success" role="alert" v-if="success" v-html="t$('settings.messages.success')"></div>

        <div class="alert alert-danger" role="alert" v-if="errorEmailExists"
             v-html="t$('register.messages.error.emailexists')"></div>

        <form name="form" id="settings-form" role="form" v-on:submit.prevent="save()" v-if="settingsAccount" novalidate>
          <div class="form-group">
            <label class="form-control-label" for="firstName" v-text="t$('settings.form.firstname')"></label>
            <input
              type="text"
              class="form-control"
              id="firstName"
              name="firstName"
              v-bind:placeholder="t$('settings.form[\'firstname.placeholder\']')"
              :class="{ valid: !v$.settingsAccount.firstName.$invalid, invalid: v$.settingsAccount.firstName.$invalid }"
              v-model="v$.settingsAccount.firstName.$model"
              minlength="1"
              maxlength="50"
              required
              data-cy="firstname"
            />
            <div v-if="v$.settingsAccount.firstName.$anyDirty && v$.settingsAccount.firstName.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.firstName.required"
                v-text="t$('settings.messages.validate.firstname.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.firstName.minLength"
                v-text="t$('settings.messages.validate.firstname.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.firstName.maxLength"
                v-text="t$('settings.messages.validate.firstname.maxlength')"
              ></small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="lastName" v-text="t$('settings.form.lastname')"></label>
            <input
              type="text"
              class="form-control"
              id="lastName"
              name="lastName"
              v-bind:placeholder="t$('settings.form[\'lastname.placeholder\']')"
              :class="{ valid: !v$.settingsAccount.lastName.$invalid, invalid: v$.settingsAccount.lastName.$invalid }"
              v-model="v$.settingsAccount.lastName.$model"
              minlength="1"
              maxlength="50"
              required
              data-cy="lastname"
            />
            <div v-if="v$.settingsAccount.lastName.$anyDirty && v$.settingsAccount.lastName.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.lastName.required"
                v-text="t$('settings.messages.validate.lastname.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.lastName.minLength"
                v-text="t$('settings.messages.validate.lastname.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.lastName.maxLength"
                v-text="t$('settings.messages.validate.lastname.maxlength')"
              ></small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="email" v-text="t$('global.form[\'email.label\']')"></label>
            <input
              type="email"
              class="form-control"
              id="email"
              name="email"
              v-bind:placeholder="t$('global.form[\'email.placeholder\']')"
              :class="{ valid: !v$.settingsAccount.email.$invalid, invalid: v$.settingsAccount.email.$invalid }"
              v-model="v$.settingsAccount.email.$model"
              minlength="5"
              maxlength="254"
              email
              required
              data-cy="email"
            />
            <div v-if="v$.settingsAccount.email.$anyDirty && v$.settingsAccount.email.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.email.required"
                v-text="t$('global.messages.validate.email.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.email.email"
                v-text="t$('global.messages.validate.email.invalid')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.email.minLength"
                v-text="t$('global.messages.validate.email.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.settingsAccount.email.maxLength"
                v-text="t$('global.messages.validate.email.maxlength')"
              ></small>
            </div>
          </div>
          <div class="form-group" v-if="languages && Object.keys(languages).length > 1">
            <label for="langKey" v-text="t$('settings.form.language')"></label>
            <select class="form-control" id="langKey" name="langKey" v-model="settingsAccount.langKey"
                    data-cy="langKey">
              <option v-for="(language, key) in languages" :value="key" :key="`lang-${key}`">{{ language.name }}
              </option>
            </select>
          </div>
          <button
            type="submit"
            :disabled="v$.settingsAccount.$invalid"
            class="btn btn-primary"
            v-text="t$('settings.form.button')"
            data-cy="submit"
          ></button>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./settings.component.ts"></script>
