// src/main/webapp/app/admin/logs/logs.vue
<template>
  <div class="table-responsive">
    <h2 id="logs-page-heading" v-text="t$('logs.title')" data-cy="logsPageHeading"></h2>

    <div v-if="loggers">
      <p v-text="t$('logs.nbloggers', { total: loggers.length })"></p>

      <span v-text="t$('logs.filter')"></span> <input type="text" v-model="filtered" class="form-control" />

      <table class="table table-sm table-striped table-bordered" aria-describedby="Logs">
        <thead>
        <tr title="click to order">
          <th v-on:click="changeOrder('name')" scope="col"><span v-text="t$('logs.table.name')"></span></th>
          <th v-on:click="changeOrder('level')" scope="col"><span v-text="t$('logs.table.level')"></span></th>
        </tr>
        </thead>

        <tr v-for="logger in filteredLoggers" :key="logger.name">
          <td>
            <small>{{ logger.name }}</small>
          </td>
          <td>
            <button
              v-on:click="updateLevel(logger.name, 'TRACE')"
              :class="logger.level === 'TRACE' ? 'btn-primary' : 'btn-light'"
              class="btn btn-sm"
            >
              TRACE
            </button>
            <button
              v-on:click="updateLevel(logger.name, 'DEBUG')"
              :class="logger.level === 'DEBUG' ? 'btn-success' : 'btn-light'"
              class="btn btn-sm"
            >
              DEBUG
            </button>
            <button
              v-on:click="updateLevel(logger.name, 'INFO')"
              :class="logger.level === 'INFO' ? 'btn-info' : 'btn-light'"
              class="btn btn-sm"
            >
              INFO
            </button>
            <button
              v-on:click="updateLevel(logger.name, 'WARN')"
              :class="logger.level === 'WARN' ? 'btn-warning' : 'btn-light'"
              class="btn btn-sm"
            >
              WARN
            </button>
            <button
              v-on:click="updateLevel(logger.name, 'ERROR')"
              :class="logger.level === 'ERROR' ? 'btn-danger' : 'btn-light'"
              class="btn btn-sm"
            >
              ERROR
            </button>
            <button
              v-on:click="updateLevel(logger.name, 'OFF')"
              :class="logger.level === 'OFF' ? 'btn-secondary' : 'btn-light'"
              class="btn btn-sm"
            >
              OFF
            </button>
          </td>
        </tr>
      </table>
    </div>
  </div>
</template>

<script lang="ts" src="./logs.component.ts"></script>

// src/main/webapp/app/admin/logs/logs.component.ts
import { Component, OnInit } from '@angular/core';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule } from '@angular/forms';
import { SortDirective, SortByDirective } from 'app/shared/sort';
import { Log, LoggersResponse, Level } from './log.model';
import { LogsService } from './logs.service';

@Component({
  standalone: true,
  selector: 'mmse-logs',
  templateUrl: './logs.component.html',
  imports: [SharedModule, FormsModule, SortDirective, SortByDirective],
})
export default class LogsComponent implements OnInit {
  loggers?: Log[];
  filteredAndOrderedLoggers?: Log[];
  isLoading = false;
  filter = '';
  orderProp: keyof Log = 'name';
  ascending = true;

  constructor(private logsService: LogsService) {}

  ngOnInit(): void {
    this.findAndExtractLoggers();
  }

  changeLevel(name: string, level: Level): void {
    this.logsService.changeLevel(name, level).subscribe(() => this.findAndExtractLoggers());
  }

  filterAndSort(): void {
    this.filteredAndOrderedLoggers = this.loggers!.filter(
      logger => !this.filter || logger.name.toLowerCase().includes(this.filter.toLowerCase())
    ).sort((a, b) => {
      if (a[this.orderProp] < b[this.orderProp]) {
        return this.ascending ? -1 : 1;
      } else if (a[this.orderProp] > b[this.orderProp]) {
        return this.ascending ? 1 : -1;
      } else if (this.orderProp === 'level') {
        return a.name < b.name ? -1 : 1;
      }
      return 0;
    });
  }

  private findAndExtractLoggers(): void {
    this.isLoading = true;
    this.logsService
      .findAll()
      .pipe(
        finalize(() => {
          this.filterAndSort();
          this.isLoading = false;
        })
      )
      .subscribe({
        next: (response: LoggersResponse) =>
          (this.loggers = Object.entries(response.loggers).map(([key, logger]) => new Log(key, logger.effectiveLevel))),
        error: () => (this.loggers = []),
      });
  }
}

<div class="table-responsive" *ngIf="loggers">
  <h2 id="logs-page-heading" mmseTranslate="logs.title" data-cy="logsPageHeading">Logs</h2>

  <div class="float-end me-3" *ngIf="isLoading">
    <div class="spinner-border"></div>
  </div>

  <p mmseTranslate="logs.nbloggers" [translateValues]="{ total: loggers.length }">There are {{ loggers.length }} loggers.</p>

  <span mmseTranslate="logs.filter">Filter</span>
  <input type="text" [(ngModel)]="filter" (ngModelChange)="filterAndSort()" class="form-control" />

  <table class="table table-sm table-striped table-bordered" aria-describedby="logs-page-heading">
    <thead>
      <tr mmseSort [(predicate)]="orderProp" [(ascending)]="ascending" (sortChange)="filterAndSort()">
        <th mmseSortBy="name" scope="col"><span mmseTranslate="logs.table.name">Name</span> <fa-icon icon="sort"></fa-icon></th>
        <th mmseSortBy="level" scope="col"><span mmseTranslate="logs.table.level">Level</span> <fa-icon icon="sort"></fa-icon></th>
      </tr>
    </thead>

    <tbody>
      <tr *ngFor="let logger of filteredAndOrderedLoggers">
        <td>
          <small>{{ logger.name | slice : 0 : 140 }}</small>
        </td>
        <td>
          <button
            (click)="changeLevel(logger.name, 'TRACE')"
            [ngClass]="logger.level === 'TRACE' ? 'btn-primary' : 'btn-light'"
            class="btn btn-sm"
          >
            TRACE
          </button>

          <button
            (click)="changeLevel(logger.name, 'DEBUG')"
            [ngClass]="logger.level === 'DEBUG' ? 'btn-success' : 'btn-light'"
            class="btn btn-sm"
          >
            DEBUG
          </button>

          <button
            (click)="changeLevel(logger.name, 'INFO')"
            [ngClass]="logger.level === 'INFO' ? 'btn-info' : 'btn-light'"
            class="btn btn-sm"
          >
            INFO
          </button>

          <button
            (click)="changeLevel(logger.name, 'WARN')"
            [ngClass]="logger.level === 'WARN' ? 'btn-warning' : 'btn-light'"
            class="btn btn-sm"
          >
            WARN
          </button>

          <button
            (click)="changeLevel(logger.name, 'ERROR')"
            [ngClass]="logger.level === 'ERROR' ? 'btn-danger' : 'btn-light'"
            class="btn btn-sm"
          >
            ERROR
          </button>

          <button
            (click)="changeLevel(logger.name, 'OFF')"
            [ngClass]="logger.level === 'OFF' ? 'btn-secondary' : 'btn-light'"
            class="btn btn-sm"
          >
            OFF
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
