// src/main/webapp/app/entities/test-entity/list/test-entity.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders } from '@angular/common/http';
import { ActivatedRoute, Data, ParamMap, Router, RouterModule } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { SortDirective, SortByDirective } from 'app/shared/sort';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { FormsModule } from '@angular/forms';
import { ITestEntity } from '../test-entity.model';

import { ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, TestEntityService } from '../service/test-entity.service';
import { TestEntityDeleteDialogComponent } from '../delete/test-entity-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';
import { InfiniteScrollModule } from 'ngx-infinite-scroll';

@Component({
  standalone: true,
  selector: 'mmse-test-entity',
  templateUrl: './test-entity.component.html',
  imports: [
    RouterModule,
    FormsModule,
    SharedModule,
    SortDirective,
    SortByDirective,
    DurationPipe,
    FormatMediumDatetimePipe,
    FormatMediumDatePipe,
    InfiniteScrollModule,
  ],
})
export class TestEntityComponent implements OnInit {
  testEntities?: ITestEntity[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  itemsPerPage = ITEMS_PER_PAGE;
  links: { [key: string]: number } = {
    last: 0,
  };
  page = 1;

  constructor(
    protected testEntityService: TestEntityService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected parseLinks: ParseLinks,
    protected modalService: NgbModal
  ) {}

  reset(): void {
    this.page = 1;
    this.testEntities = [];
    this.load();
  }

  loadPage(page: number): void {
    this.page = page;
    this.load();
  }

  trackId = (_index: number, item: ITestEntity): number => this.testEntityService.getTestEntityIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(testEntity: ITestEntity): void {
    const modalRef = this.modalService.open(TestEntityDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.testEntity = testEntity;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.page, this.predicate, this.ascending);
  }

  navigateToPage(page = this.page): void {
    this.handleNavigation(page, this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.page, this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    this.fillComponentAttributesFromResponseHeader(response.headers);
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.testEntities = dataFromBody;
  }

  protected fillComponentAttributesFromResponseBody(data: ITestEntity[] | null): ITestEntity[] {
    // If there is previus link, data is a infinite scroll pagination content.
    if ('prev' in this.links) {
      const testEntitiesNew = this.testEntities ?? [];
      if (data) {
        for (const d of data) {
          if (testEntitiesNew.map(op => op.id).indexOf(d.id) === -1) {
            testEntitiesNew.push(d);
          }
        }
      }
      return testEntitiesNew;
    }
    return data ?? [];
  }

  protected fillComponentAttributesFromResponseHeader(headers: HttpHeaders): void {
    const linkHeader = headers.get('link');
    if (linkHeader) {
      this.links = this.parseLinks.parse(linkHeader);
    } else {
      this.links = {
        last: 0,
      };
    }
  }

  protected queryBackend(page?: number, predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const pageToLoad: number = page ?? 1;
    const queryObject: any = {
      page: pageToLoad - 1,
      size: this.itemsPerPage,
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.testEntityService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(page = this.page, predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      page,
      size: this.itemsPerPage,
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="TestEntityHeading">
    <span mmseTranslate="mmseApp.testEntity.home.title">Test Entities</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span mmseTranslate="mmseApp.testEntity.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-test-entity"
        [routerLink]="['/test-entity/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span mmseTranslate="mmseApp.testEntity.home.createLabel"> Create a new Test Entity </span>
      </button>
    </div>
  </h2>

  <mmse-alert-error></mmse-alert-error>

  <mmse-alert></mmse-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="testEntities?.length === 0">
    <span mmseTranslate="mmseApp.testEntity.home.notFound">No Test Entities found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="testEntities && testEntities.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr mmseSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" mmseSortBy="id">
            <div class="d-flex">
              <span mmseTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" mmseSortBy="createdAt">
            <div class="d-flex">
              <span mmseTranslate="mmseApp.testEntity.createdAt">Created At</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" mmseSortBy="updatedAt">
            <div class="d-flex">
              <span mmseTranslate="mmseApp.testEntity.updatedAt">Updated At</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" mmseSortBy="score">
            <div class="d-flex">
              <span mmseTranslate="mmseApp.testEntity.score">Score</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" mmseSortBy="user.login">
            <div class="d-flex">
              <span mmseTranslate="mmseApp.testEntity.user">User</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody
        infinite-scroll
        (scrolled)="loadPage(page + 1)"
        [infiniteScrollDisabled]="page - 1 >= links['last']"
        [infiniteScrollDistance]="0"
      >
        <tr *ngFor="let testEntity of testEntities; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/test-entity', testEntity.id, 'view']">{{ testEntity.id }}</a>
          </td>
          <td>{{ testEntity.createdAt | formatMediumDatetime }}</td>
          <td>{{ testEntity.updatedAt | formatMediumDatetime }}</td>
          <td>{{ testEntity.score }}</td>
          <td>
            {{ testEntity.user?.login }}
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/test-entity', testEntity.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" mmseTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/test-entity', testEntity.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" mmseTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(testEntity)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" mmseTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/test-entity/test-entity.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="TestEntityHeading">
      <span v-text="t$('mmseApp.testEntity.home.title')" id="test-entity-heading"></span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="t$('mmseApp.testEntity.home.refreshListLabel')"></span>
        </button>
        <router-link :to="{ name: 'TestEntityCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-test-entity"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="t$('mmseApp.testEntity.home.createLabel')"></span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && testEntities && testEntities.length === 0">
      <span v-text="t$('mmseApp.testEntity.home.notFound')"></span>
    </div>
    <div class="table-responsive" v-if="testEntities && testEntities.length > 0">
      <table class="table table-striped" aria-describedby="testEntities">
        <thead>
        <tr>
          <th scope="row" v-on:click="changeOrder('id')">
            <span v-text="t$('global.field.id')"></span>
            <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
          </th>
          <th scope="row" v-on:click="changeOrder('createdAt')">
            <span v-text="t$('mmseApp.testEntity.createdAt')"></span>
            <jhi-sort-indicator :current-order="propOrder" :reverse="reverse"
                                :field-name="'createdAt'"></jhi-sort-indicator>
          </th>
          <th scope="row" v-on:click="changeOrder('updatedAt')">
            <span v-text="t$('mmseApp.testEntity.updatedAt')"></span>
            <jhi-sort-indicator :current-order="propOrder" :reverse="reverse"
                                :field-name="'updatedAt'"></jhi-sort-indicator>
          </th>
          <th scope="row" v-on:click="changeOrder('score')">
            <span v-text="t$('mmseApp.testEntity.score')"></span>
            <jhi-sort-indicator :current-order="propOrder" :reverse="reverse"
                                :field-name="'score'"></jhi-sort-indicator>
          </th>
          <th scope="row" v-on:click="changeOrder('user.login')">
            <span v-text="t$('mmseApp.testEntity.user')"></span>
            <jhi-sort-indicator :current-order="propOrder" :reverse="reverse"
                                :field-name="'user.login'"></jhi-sort-indicator>
          </th>
          <th scope="row"></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="testEntity in testEntities" :key="testEntity.id" data-cy="entityTable">
          <td>
            <router-link :to="{ name: 'TestEntityView', params: { testEntityId: testEntity.id } }">{{ testEntity.id }}
            </router-link>
          </td>
          <td>{{ formatDateShort(testEntity.createdAt) || "" }}</td>
          <td>{{ formatDateShort(testEntity.updatedAt) || "" }}</td>
          <td>{{ testEntity.score }}</td>
          <td>
            {{ testEntity.user ? testEntity.user.login : "" }}
          </td>
          <td class="text-right">
            <div class="btn-group">
              <router-link :to="{ name: 'TestEntityView', params: { testEntityId: testEntity.id } }" custom
                           v-slot="{ navigate }">
                <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                  <font-awesome-icon icon="eye"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="t$('entity.action.view')"></span>
                </button>
              </router-link>
              <router-link :to="{ name: 'TestEntityEdit', params: { testEntityId: testEntity.id } }" custom
                           v-slot="{ navigate }">
                <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                  <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="t$('entity.action.edit')"></span>
                </button>
              </router-link>
              <b-button
                v-on:click="prepareRemove(testEntity)"
                variant="danger"
                class="btn btn-sm"
                data-cy="entityDeleteButton"
                v-b-modal.removeEntity
              >
                <font-awesome-icon icon="times"></font-awesome-icon>
                <span class="d-none d-md-inline" v-text="t$('entity.action.delete')"></span>
              </b-button>
            </div>
          </td>
        </tr>
        </tbody>
        <span ref="infiniteScrollEl"></span>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <template #modal-title>
        <span id="mmseApp.testEntity.delete.question" data-cy="testEntityDeleteDialogHeading"
              v-text="t$('entity.delete.title')"></span>
      </template>
      <div class="modal-body">
        <p id="mmse-delete-testEntity-heading" v-text="t$('mmseApp.testEntity.delete.question', { id: removeId })"></p>
      </div>
      <template #modal-footer>
        <div>
          <button type="button" class="btn btn-secondary" v-text="t$('entity.action.cancel')"
                  v-on:click="closeDialog()"></button>
          <button
            type="button"
            class="btn btn-primary"
            id="mmse-confirm-delete-testEntity"
            data-cy="entityConfirmDeleteButton"
            v-text="t$('entity.action.delete')"
            v-on:click="removeTestEntity()"
          ></button>
        </div>
      </template>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./test-entity.component.ts"></script>
