// src/main/webapp/app/entities/user-answer/update/user-answer-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { UserAnswerFormService, UserAnswerFormGroup } from './user-answer-form.service';
import { IUserAnswer } from '../user-answer.model';
import { UserAnswerService } from '../service/user-answer.service';
import { ITestEntity } from 'app/entities/test-entity/test-entity.model';
import { TestEntityService } from 'app/entities/test-entity/service/test-entity.service';
import { QuestionId } from 'app/entities/enumerations/question-id.model';

@Component({
  standalone: true,
  selector: 'mmse-user-answer-update',
  templateUrl: './user-answer-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class UserAnswerUpdateComponent implements OnInit {
  isSaving = false;
  userAnswer: IUserAnswer | null = null;
  questionIdValues = Object.keys(QuestionId);

  testEntitiesSharedCollection: ITestEntity[] = [];

  editForm: UserAnswerFormGroup = this.userAnswerFormService.createUserAnswerFormGroup();

  constructor(
    protected userAnswerService: UserAnswerService,
    protected userAnswerFormService: UserAnswerFormService,
    protected testEntityService: TestEntityService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareTestEntity = (o1: ITestEntity | null, o2: ITestEntity | null): boolean => this.testEntityService.compareTestEntity(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ userAnswer }) => {
      this.userAnswer = userAnswer;
      if (userAnswer) {
        this.updateForm(userAnswer);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const userAnswer = this.userAnswerFormService.getUserAnswer(this.editForm);
    if (userAnswer.id !== null) {
      this.subscribeToSaveResponse(this.userAnswerService.update(userAnswer));
    } else {
      this.subscribeToSaveResponse(this.userAnswerService.create(userAnswer));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IUserAnswer>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(userAnswer: IUserAnswer): void {
    this.userAnswer = userAnswer;
    this.userAnswerFormService.resetForm(this.editForm, userAnswer);

    this.testEntitiesSharedCollection = this.testEntityService.addTestEntityToCollectionIfMissing<ITestEntity>(
      this.testEntitiesSharedCollection,
      userAnswer.testEntity
    );
  }

  protected loadRelationshipsOptions(): void {
    this.testEntityService
      .query()
      .pipe(map((res: HttpResponse<ITestEntity[]>) => res.body ?? []))
      .pipe(
        map((testEntities: ITestEntity[]) =>
          this.testEntityService.addTestEntityToCollectionIfMissing<ITestEntity>(testEntities, this.userAnswer?.testEntity)
        )
      )
      .subscribe((testEntities: ITestEntity[]) => (this.testEntitiesSharedCollection = testEntities));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="mmse-user-answer-heading" data-cy="UserAnswerCreateUpdateHeading" mmseTranslate="mmseApp.userAnswer.home.createOrEditLabel">
        Create or edit a User Answer
      </h2>

      <div>
        <mmse-alert-error></mmse-alert-error>

        <div class="mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" mmseTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="mb-3">
          <label class="form-label" mmseTranslate="mmseApp.userAnswer.answerText" for="field_answerText">Answer Text</label>
          <input
            type="text"
            class="form-control"
            name="answerText"
            id="field_answerText"
            data-cy="answerText"
            formControlName="answerText"
          />
        </div>

        <div class="mb-3">
          <label class="form-label" mmseTranslate="mmseApp.userAnswer.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              mmseTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.datetimelocal"
              mmseTranslate="entity.validation.datetimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" mmseTranslate="mmseApp.userAnswer.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" mmseTranslate="mmseApp.userAnswer.questionId" for="field_questionId">Question Id</label>
          <select class="form-control" name="questionId" formControlName="questionId" id="field_questionId" data-cy="questionId">
            <option [ngValue]="null">{{ 'mmseApp.QuestionId.null' | translate }}</option>
            <option *ngFor="let questionId of questionIdValues" [value]="questionId">
              {{ 'mmseApp.QuestionId.' + questionId | translate }}
            </option>
          </select>
          <div *ngIf="editForm.get('questionId')!.invalid && (editForm.get('questionId')!.dirty || editForm.get('questionId')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('questionId')?.errors?.required"
              mmseTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" mmseTranslate="mmseApp.userAnswer.testEntity" for="field_testEntity">Test Entity</label>
          <select
            class="form-control"
            id="field_testEntity"
            data-cy="testEntity"
            name="testEntity"
            formControlName="testEntity"
            [compareWith]="compareTestEntity"
          >
            <option *ngIf="!editForm.get('testEntity')!.value" [ngValue]="null" selected></option>
            <option [ngValue]="testEntityOption" *ngFor="let testEntityOption of testEntitiesSharedCollection">
              {{ testEntityOption.id }}
            </option>
          </select>
        </div>
        <div
          *ngIf="editForm.get(['testEntity'])!.invalid && (editForm.get(['testEntity'])!.dirty || editForm.get(['testEntity'])!.touched)"
        >
          <small
            class="form-text text-danger"
            *ngIf="editForm.get(['testEntity'])?.errors?.required"
            mmseTranslate="entity.validation.required"
          >
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span mmseTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span mmseTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/user-answer/user-answer-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="mmseApp.userAnswer.home.createOrEditLabel"
          data-cy="UserAnswerCreateUpdateHeading"
          v-text="t$('mmseApp.userAnswer.home.createOrEditLabel')"
        ></h2>
        <div>
          <div class="form-group" v-if="userAnswer.id">
            <label for="id" v-text="t$('global.field.id')"></label>
            <input type="text" class="form-control" id="id" name="id" v-model="userAnswer.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('mmseApp.userAnswer.answerText')"
                   for="user-answer-answerText"></label>
            <input
              type="text"
              class="form-control"
              name="answerText"
              id="user-answer-answerText"
              data-cy="answerText"
              :class="{ valid: !v$.answerText.$invalid, invalid: v$.answerText.$invalid }"
              v-model="v$.answerText.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('mmseApp.userAnswer.createdAt')"
                   for="user-answer-createdAt"></label>
            <div class="d-flex">
              <input
                id="user-answer-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !v$.createdAt.$invalid, invalid: v$.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer(v$.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="v$.createdAt.$anyDirty && v$.createdAt.$invalid">
              <small class="form-text text-danger" v-for="error of v$.createdAt.$errors"
                     :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('mmseApp.userAnswer.updatedAt')"
                   for="user-answer-updatedAt"></label>
            <div class="d-flex">
              <input
                id="user-answer-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !v$.updatedAt.$invalid, invalid: v$.updatedAt.$invalid }"
                :value="convertDateTimeFromServer(v$.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('mmseApp.userAnswer.questionId')"
                   for="user-answer-questionId"></label>
            <select
              class="form-control"
              name="questionId"
              :class="{ valid: !v$.questionId.$invalid, invalid: v$.questionId.$invalid }"
              v-model="v$.questionId.$model"
              id="user-answer-questionId"
              data-cy="questionId"
              required
            >
              <option
                v-for="questionId in questionIdValues"
                :key="questionId"
                v-bind:value="questionId"
                v-bind:label="t$('mmseApp.QuestionId.' + questionId)"
              >
                {{ questionId }}
              </option>
            </select>
            <div v-if="v$.questionId.$anyDirty && v$.questionId.$invalid">
              <small class="form-text text-danger" v-for="error of v$.questionId.$errors"
                     :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('mmseApp.userAnswer.testEntity')"
                   for="user-answer-testEntity"></label>
            <select
              class="form-control"
              id="user-answer-testEntity"
              data-cy="testEntity"
              name="testEntity"
              v-model="userAnswer.testEntity"
              required
            >
              <option v-if="!userAnswer.testEntity" v-bind:value="null" selected></option>
              <option
                v-bind:value="
                  userAnswer.testEntity && testEntityOption.id === userAnswer.testEntity.id ? userAnswer.testEntity : testEntityOption
                "
                v-for="testEntityOption in testEntities"
                :key="testEntityOption.id"
              >
                {{ testEntityOption.id }}
              </option>
            </select>
          </div>
          <div v-if="v$.testEntity.$anyDirty && v$.testEntity.$invalid">
            <small class="form-text text-danger" v-for="error of v$.testEntity.$errors"
                   :key="error.$uid">{{ error.$message }}</small>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary"
                  v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.cancel')"></span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="v$.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.save')"></span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./user-answer-update.component.ts"></script>
