// src/main/webapp/app/admin/health/health.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { HealthService } from './health.service';
import { Health, HealthDetails, HealthStatus } from './health.model';
import HealthModalComponent from './modal/health-modal.component';

@Component({
  standalone: true,
  selector: 'mmse-health',
  templateUrl: './health.component.html',
  imports: [SharedModule, HealthModalComponent],
})
export default class HealthComponent implements OnInit {
  health?: Health;

  constructor(private modalService: NgbModal, private healthService: HealthService) {}

  ngOnInit(): void {
    this.refresh();
  }

  getBadgeClass(statusState: HealthStatus): string {
    if (statusState === 'UP') {
      return 'bg-success';
    }
    return 'bg-danger';
  }

  refresh(): void {
    this.healthService.checkHealth().subscribe({
      next: health => (this.health = health),
      error: (error: HttpErrorResponse) => {
        if (error.status === 503) {
          this.health = error.error;
        }
      },
    });
  }

  showHealth(health: { key: string; value: HealthDetails }): void {
    const modalRef = this.modalService.open(HealthModalComponent);
    modalRef.componentInstance.health = health;
  }
}

<div>
  <h2>
    <span id="health-page-heading" mmseTranslate="health.title" data-cy="healthPageHeading">Health Checks</span>

    <button class="btn btn-primary float-end" (click)="refresh()">
      <fa-icon icon="sync"></fa-icon> <span mmseTranslate="health.refresh.button">Refresh</span>
    </button>
  </h2>

  <div class="table-responsive">
    <table id="healthCheck" class="table table-striped" aria-describedby="health-page-heading">
      <thead>
        <tr>
          <th scope="col" mmseTranslate="health.table.service">Service name</th>
          <th scope="col" class="text-center" mmseTranslate="health.table.status">Status</th>
          <th scope="col" class="text-center" mmseTranslate="health.details.details">Details</th>
        </tr>
      </thead>
      <tbody *ngIf="health">
        <tr *ngFor="let componentHealth of health.components | keyvalue">
          <td>
            {{ 'health.indicator.' + componentHealth.key | translate }}
          </td>
          <td class="text-center">
            <span
              class="badge"
              [ngClass]="getBadgeClass(componentHealth.value!.status)"
              mmseTranslate="{{ 'health.status.' + componentHealth.value!.status }}"
            >
              {{
                { UNKNOWN: 'UNKNOWN', UP: 'UP', OUT_OF_SERVICE: 'OUT_OF_SERVICE', DOWN: 'DOWN' }[componentHealth.value!.status || 'UNKNOWN']
              }}
            </span>
          </td>
          <td class="text-center">
            <a
              class="hand"
              (click)="showHealth({ key: componentHealth.key, value: componentHealth.value! })"
              *ngIf="componentHealth.value!.details"
            >
              <fa-icon icon="eye"></fa-icon>
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/admin/health/health.vue
<template>
  <div>
    <h2>
      <span id="health-page-heading" v-text="t$('health.title')" data-cy="healthPageHeading"></span>
      <button class="btn btn-primary float-right" v-on:click="refresh()" :disabled="updatingHealth">
        <font-awesome-icon icon="sync"></font-awesome-icon>
        <span v-text="t$('health[\'refresh.button\']')"></span>
      </button>
    </h2>
    <div class="table-responsive">
      <table id="healthCheck" class="table table-striped" aria-describedby="Health check">
        <thead>
        <tr>
          <th v-text="t$('health.table.service')" scope="col"></th>
          <th class="text-center" v-text="t$('health.table.status')" scope="col"></th>
          <th class="text-center" v-text="t$('health.details.details')" scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="health of healthData" :key="health.name">
          <td><span v-text="t$('health.indicator.' + baseName(health.name))" /> {{ subSystemName(health.name) }}</td>
          <td class="text-center">
            <span class="badge" :class="getBadgeClass(health.status)"
                  v-text="t$('health.status.' + health.status)"></span>
          </td>
          <td class="text-center">
            <a class="hand" v-on:click="showHealth(health)" v-if="health.details || health.error">
              <font-awesome-icon icon="eye"></font-awesome-icon>
            </a>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="healthModal">
      <template #modal-title>
        <h4 v-if="currentHealth" class="modal-title" id="showHealthLabel">
          <span v-text="t$('health.indicator.' + baseName(currentHealth.name))" />
          {{ subSystemName(currentHealth.name) }}
        </h4>
      </template>
      <health-modal :current-health="currentHealth"></health-modal>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./health.component.ts"></script>
