// src/main/webapp/app/account/register/register.vue
<template>
  <div>
    <div class="row justify-content-center">
      <div class="col-md-8 toastify-container">
        <h1 v-text="t$('register.title')" id="register-title" data-cy="registerTitle"></h1>

        <div class="alert alert-success" role="alert" v-if="success" v-html="t$('register.messages.success')"></div>

        <div class="alert alert-danger" role="alert" v-if="error" v-html="t$('register.messages.error.fail')"></div>

        <div class="alert alert-danger" role="alert" v-if="errorUserExists"
             v-html="t$('register.messages.error.userexists')"></div>

        <div class="alert alert-danger" role="alert" v-if="errorEmailExists"
             v-html="t$('register.messages.error.emailexists')"></div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-8">
        <form id="register-form" name="registerForm" role="form" v-on:submit.prevent="register()" v-if="!success"
              no-validate>
          <div class="form-group">
            <label class="form-control-label" for="username" v-text="t$('global.form[\'username.label\']')"></label>
            <input
              type="text"
              class="form-control"
              v-model="v$.registerAccount.login.$model"
              id="username"
              name="login"
              :class="{ valid: !v$.registerAccount.login.$invalid, invalid: v$.registerAccount.login.$invalid }"
              required
              minlength="1"
              maxlength="50"
              pattern="^[a-zA-Z0-9!#$&'*+=?^_`{|}~.-]+@?[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$"
              v-bind:placeholder="t$('global.form[\'username.placeholder\']')"
              data-cy="username"
            />
            <div v-if="v$.registerAccount.login.$anyDirty && v$.registerAccount.login.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.login.required"
                v-text="t$('register.messages.validate.login.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.login.minLength"
                v-text="t$('register.messages.validate.login.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.login.maxLength"
                v-text="t$('register.messages.validate.login.maxlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.login.pattern"
                v-text="t$('register.messages.validate.login.pattern')"
              ></small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="email" v-text="t$('global.form[\'email.label\']')"></label>
            <input
              type="email"
              class="form-control"
              id="email"
              name="email"
              :class="{ valid: !v$.registerAccount.email.$invalid, invalid: v$.registerAccount.email.$invalid }"
              v-model="v$.registerAccount.email.$model"
              minlength="5"
              maxlength="254"
              email
              required
              v-bind:placeholder="t$('global.form[\'email.placeholder\']')"
              data-cy="email"
            />
            <div v-if="v$.registerAccount.email.$anyDirty && v$.registerAccount.email.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.email.required"
                v-text="t$('global.messages.validate.email.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.email.email"
                v-text="t$('global.messages.validate.email.invalid')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.email.minLength"
                v-text="t$('global.messages.validate.email.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.email.maxLength"
                v-text="t$('global.messages.validate.email.maxlength')"
              ></small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="firstPassword"
                   v-text="t$('global.form[\'newpassword.label\']')"></label>
            <input
              type="password"
              class="form-control"
              id="firstPassword"
              name="password"
              :class="{ valid: !v$.registerAccount.password.$invalid, invalid: v$.registerAccount.password.$invalid }"
              v-model="v$.registerAccount.password.$model"
              minlength="4"
              maxlength="50"
              required
              v-bind:placeholder="t$('global.form[\'newpassword.placeholder\']')"
              data-cy="firstPassword"
            />
            <div v-if="v$.registerAccount.password.$anyDirty && v$.registerAccount.password.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.password.required"
                v-text="t$('global.messages.validate.newpassword.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.password.minLength"
                v-text="t$('global.messages.validate.newpassword.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.registerAccount.password.maxLength"
                v-text="t$('global.messages.validate.newpassword.maxlength')"
              ></small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="secondPassword"
                   v-text="t$('global.form[\'confirmpassword.label\']')"></label>
            <input
              type="password"
              class="form-control"
              id="secondPassword"
              name="confirmPasswordInput"
              :class="{ valid: !v$.confirmPassword.$invalid, invalid: v$.confirmPassword.$invalid }"
              v-model="v$.confirmPassword.$model"
              minlength="4"
              maxlength="50"
              required
              v-bind:placeholder="t$('global.form[\'confirmpassword.placeholder\']')"
              data-cy="secondPassword"
            />
            <div v-if="v$.confirmPassword.$dirty && v$.confirmPassword.$invalid">
              <small
                class="form-text text-danger"
                v-if="!v$.confirmPassword.required"
                v-text="t$('global.messages.validate.confirmpassword.required')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.confirmPassword.minLength"
                v-text="t$('global.messages.validate.confirmpassword.minlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.confirmPassword.maxLength"
                v-text="t$('global.messages.validate.confirmpassword.maxlength')"
              ></small>
              <small
                class="form-text text-danger"
                v-if="!v$.confirmPassword.sameAsPassword"
                v-text="t$('global.messages.error.dontmatch')"
              ></small>
            </div>
          </div>

          <button
            type="submit"
            :disabled="v$.$invalid"
            class="btn btn-primary"
            v-text="t$('register.form.button')"
            data-cy="submit"
          ></button>
        </form>
        <p></p>
        <div class="alert alert-warning">
          <span v-text="t$('global.messages.info.authenticated.prefix')"></span>
          <a class="alert-link" v-on:click="openLogin()" v-text="t$('global.messages.info.authenticated.link')"></a
          ><span v-html="t$('global.messages.info.authenticated.suffix')"></span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./register.component.ts"></script>

// src/main/webapp/app/account/register/register.component.ts
import {AfterViewInit, Component, ElementRef, ViewChild} from '@angular/core';
import {HttpErrorResponse} from '@angular/common/http';
import {RouterModule} from '@angular/router';
import {FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators} from '@angular/forms';
import {TranslateService} from '@ngx-translate/core';

import {EMAIL_ALREADY_USED_TYPE, LOGIN_ALREADY_USED_TYPE} from 'app/config/error.constants';
import {RegisterService} from './register.service';
import SharedModule from 'app/shared/shared.module';
import PasswordStrengthBarComponent from '../password/password-strength-bar/password-strength-bar.component';

@Component({
  selector: 'mmse-register',
  standalone: true,
  imports: [SharedModule, RouterModule, FormsModule, ReactiveFormsModule, PasswordStrengthBarComponent],
  templateUrl: './register.component.html',
})
export default class RegisterComponent implements AfterViewInit {
  @ViewChild('login', { static: false })
  login?: ElementRef;

  doNotMatch = false;
  error = false;
  errorEmailExists = false;
  errorUserExists = false;
  success = false;

  registerForm = new FormGroup({
    login: new FormControl('', {
      nonNullable: true,
      validators: [
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
        Validators.pattern('^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$'),
      ],
    }),
    email: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(5), Validators.maxLength(254), Validators.email],
    }),
    password: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(4), Validators.maxLength(50)],
    }),
    confirmPassword: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(4), Validators.maxLength(50)],
    }),
  });

  constructor(private translateService: TranslateService, private registerService: RegisterService) {}

  ngAfterViewInit(): void {
    if (this.login) {
      this.login.nativeElement.focus();
    }
  }

  register(): void {
    this.doNotMatch = false;
    this.error = false;
    this.errorEmailExists = false;
    this.errorUserExists = false;

    const { password, confirmPassword } = this.registerForm.getRawValue();
    if (password !== confirmPassword) {
      this.doNotMatch = true;
    } else {
      const { login, email } = this.registerForm.getRawValue();
      this.registerService
        .save({ login, email, password, langKey: this.translateService.currentLang })
        .subscribe({ next: () => (this.success = true), error: response => this.processError(response) });
    }
  }

  private processError(response: HttpErrorResponse): void {
    if (response.status === 400 && response.error.type === LOGIN_ALREADY_USED_TYPE) {
      this.errorUserExists = true;
    } else if (response.status === 400 && response.error.type === EMAIL_ALREADY_USED_TYPE) {
      this.errorEmailExists = true;
    } else {
      this.error = true;
    }
  }
}

<div>
  <div class="d-flex justify-content-center">
    <div class="col-md-8">
      <h1 mmseTranslate="register.title" data-cy="registerTitle">Registration</h1>

      <div class="alert alert-success" *ngIf="success" mmseTranslate="register.messages.success">
        <strong>Registration saved!</strong> Please check your email for confirmation.
      </div>

      <div class="alert alert-danger" *ngIf="error" mmseTranslate="register.messages.error.fail">
        <strong>Registration failed!</strong> Please try again later.
      </div>

      <div class="alert alert-danger" *ngIf="errorUserExists" mmseTranslate="register.messages.error.userexists">
        <strong>Login name already registered!</strong> Please choose another one.
      </div>

      <div class="alert alert-danger" *ngIf="errorEmailExists" mmseTranslate="register.messages.error.emailexists">
        <strong>Email is already in use!</strong> Please choose another one.
      </div>

      <div class="alert alert-danger" *ngIf="doNotMatch" mmseTranslate="global.messages.error.dontmatch">
        The password and its confirmation do not match!
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <div class="col-md-8">
      <form name="form" role="form" (ngSubmit)="register()" [formGroup]="registerForm" *ngIf="!success">
        <div class="mb-3">
          <label class="form-label" for="login" mmseTranslate="global.form.username.label">Username</label>
          <input
            type="text"
            class="form-control"
            id="login"
            name="login"
            placeholder="{{ 'global.form.username.placeholder' | translate }}"
            formControlName="login"
            data-cy="username"
            #login
          />

          <div *ngIf="registerForm.get('login')!.invalid && (registerForm.get('login')!.dirty || registerForm.get('login')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('login')?.errors?.required"
              mmseTranslate="register.messages.validate.login.required"
            >
              Your username is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('login')?.errors?.minlength"
              mmseTranslate="register.messages.validate.login.minlength"
            >
              Your username is required to be at least 1 character.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('login')?.errors?.maxlength"
              mmseTranslate="register.messages.validate.login.maxlength"
            >
              Your username cannot be longer than 50 characters.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('login')?.errors?.pattern"
              mmseTranslate="register.messages.validate.login.pattern"
            >
              Your username is invalid.
            </small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" for="email" mmseTranslate="global.form.email.label">Email</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="{{ 'global.form.email.placeholder' | translate }}"
            formControlName="email"
            data-cy="email"
          />

          <div *ngIf="registerForm.get('email')!.invalid && (registerForm.get('email')!.dirty || registerForm.get('email')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('email')?.errors?.required"
              mmseTranslate="global.messages.validate.email.required"
            >
              Your email is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('email')?.errors?.invalid"
              mmseTranslate="global.messages.validate.email.invalid"
            >
              Your email is invalid.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('email')?.errors?.minlength"
              mmseTranslate="global.messages.validate.email.minlength"
            >
              Your email is required to be at least 5 characters.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('email')?.errors?.maxlength"
              mmseTranslate="global.messages.validate.email.maxlength"
            >
              Your email cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" for="password" mmseTranslate="global.form.newpassword.label">New password</label>
          <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="{{ 'global.form.newpassword.placeholder' | translate }}"
            formControlName="password"
            data-cy="firstPassword"
          />

          <div
            *ngIf="registerForm.get('password')!.invalid && (registerForm.get('password')!.dirty || registerForm.get('password')!.touched)"
          >
            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('password')?.errors?.required"
              mmseTranslate="global.messages.validate.newpassword.required"
            >
              Your password is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('password')?.errors?.minlength"
              mmseTranslate="global.messages.validate.newpassword.minlength"
            >
              Your password is required to be at least 4 characters.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('password')?.errors?.maxlength"
              mmseTranslate="global.messages.validate.newpassword.maxlength"
            >
              Your password cannot be longer than 50 characters.
            </small>
          </div>

          <mmse-password-strength-bar [passwordToCheck]="registerForm.get('password')!.value"></mmse-password-strength-bar>
        </div>

        <div class="mb-3">
          <label class="form-label" for="confirmPassword" mmseTranslate="global.form.confirmpassword.label"
            >New password confirmation</label
          >
          <input
            type="password"
            class="form-control"
            id="confirmPassword"
            name="confirmPassword"
            placeholder="{{ 'global.form.confirmpassword.placeholder' | translate }}"
            formControlName="confirmPassword"
            data-cy="secondPassword"
          />

          <div
            *ngIf="
              registerForm.get('confirmPassword')!.invalid &&
              (registerForm.get('confirmPassword')!.dirty || registerForm.get('confirmPassword')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('confirmPassword')?.errors?.required"
              mmseTranslate="global.messages.validate.confirmpassword.required"
            >
              Your confirmation password is required.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('confirmPassword')?.errors?.minlength"
              mmseTranslate="global.messages.validate.confirmpassword.minlength"
            >
              Your confirmation password is required to be at least 4 characters.
            </small>

            <small
              class="form-text text-danger"
              *ngIf="registerForm.get('confirmPassword')?.errors?.maxlength"
              mmseTranslate="global.messages.validate.confirmpassword.maxlength"
            >
              Your confirmation password cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <button
          type="submit"
          [disabled]="registerForm.invalid"
          class="btn btn-primary"
          mmseTranslate="register.form.button"
          data-cy="submit"
        >
          Register
        </button>
      </form>

      <div class="mt-3 alert alert-warning">
        <span mmseTranslate="global.messages.info.authenticated.prefix">If you want to </span>
        <a class="alert-link" routerLink="/login" mmseTranslate="global.messages.info.authenticated.link">sign in</a
        ><span mmseTranslate="global.messages.info.authenticated.suffix"
          >, you can try the default accounts:<br />- Administrator (login="admin" and password="admin") <br />- User (login="user" and
          password="user").</span
        >
      </div>
    </div>
  </div>
</div>
