// src/main/webapp/app/admin/configuration/configuration.component.ts
import {Component, OnInit} from '@angular/core';

import SharedModule from 'app/shared/shared.module';
import {FormsModule} from '@angular/forms';
import {SortByDirective, SortDirective} from 'app/shared/sort';
import {ConfigurationService} from './configuration.service';
import {Bean, PropertySource} from './configuration.model';

@Component({
  standalone: true,
  selector: 'mmse-configuration',
  templateUrl: './configuration.component.html',
  imports: [SharedModule, FormsModule, SortDirective, SortByDirective],
})
export default class ConfigurationComponent implements OnInit {
  allBeans!: Bean[];
  beans: Bean[] = [];
  beansFilter = '';
  beansAscending = true;
  propertySources: PropertySource[] = [];

  constructor(private configurationService: ConfigurationService) {}

  ngOnInit(): void {
    this.configurationService.getBeans().subscribe(beans => {
      this.allBeans = beans;
      this.filterAndSortBeans();
    });

    this.configurationService.getPropertySources().subscribe(propertySources => (this.propertySources = propertySources));
  }

  filterAndSortBeans(): void {
    const beansAscendingValue = this.beansAscending ? -1 : 1;
    const beansAscendingValueReverse = this.beansAscending ? 1 : -1;
    this.beans = this.allBeans
      .filter(bean => !this.beansFilter || bean.prefix.toLowerCase().includes(this.beansFilter.toLowerCase()))
      .sort((a, b) => (a.prefix < b.prefix ? beansAscendingValue : beansAscendingValueReverse));
  }
}

<div *ngIf="allBeans">
  <h2 id="configuration-page-heading" mmseTranslate="configuration.title" data-cy="configurationPageHeading">Configuration</h2>

  <span mmseTranslate="configuration.filter">Filter (by prefix)</span>
  <input type="text" [(ngModel)]="beansFilter" (ngModelChange)="filterAndSortBeans()" class="form-control" />

  <h3 id="spring-configuration">Spring configuration</h3>

  <table class="table table-striped table-bordered table-responsive d-table" aria-describedby="spring-configuration">
    <thead>
      <tr mmseSort predicate="prefix" [(ascending)]="beansAscending" (sortChange)="filterAndSortBeans()">
        <th mmseSortBy="prefix" scope="col" class="w-40">
          <span mmseTranslate="configuration.table.prefix">Prefix</span> <fa-icon icon="sort"></fa-icon>
        </th>
        <th scope="col" class="w-60"><span mmseTranslate="configuration.table.properties">Properties</span></th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let bean of beans">
        <td>
          <span>{{ bean.prefix }}</span>
        </td>
        <td>
          <div class="row" *ngFor="let property of bean.properties | keyvalue">
            <div class="col-md-4">{{ property.key }}</div>
            <div class="col-md-8">
              <span class="float-end bg-secondary break">{{ property.value | json }}</span>
            </div>
          </div>
        </td>
      </tr>
    </tbody>
  </table>

  <div *ngFor="let propertySource of propertySources; let i = index">
    <h4 [id]="'property-source-' + i">
      <span>{{ propertySource.name }}</span>
    </h4>

    <table class="table table-sm table-striped table-bordered table-responsive d-table" [attr.aria-describedby]="'property-source-' + i">
      <thead>
        <tr>
          <th scope="col" class="w-40">Property</th>
          <th scope="col" class="w-60">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let property of propertySource.properties | keyvalue">
          <td class="break">{{ property.key }}</td>
          <td class="break">
            <span class="float-end bg-secondary break">{{ property.value.value }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/admin/configuration/configuration.vue
<template>
  <div>
    <h2 id="configuration-page-heading" v-text="t$('configuration.title')" data-cy="configurationPageHeading"></h2>

    <div v-if="allConfiguration && configuration">
      <span v-text="t$('configuration.filter')"></span> <input type="text" v-model="filtered" class="form-control" />
      <h3>Spring configuration</h3>
      <table class="table table-striped table-bordered table-responsive d-table" aria-describedby="Configuration">
        <thead>
        <tr>
          <th class="w-40" v-on:click="changeOrder('prefix')" scope="col">
            <span v-text="t$('configuration.table.prefix')"></span>
          </th>
          <th class="w-60" v-on:click="changeOrder('properties')" scope="col">
            <span v-text="t$('configuration.table.properties')"></span>
          </th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="entry in filteredConfiguration" :key="entry.prefix">
          <td>
            <span>{{ entry.prefix }}</span>
          </td>
          <td>
            <div class="row" v-for="key in keys(entry.properties)" :key="key">
              <div class="col-md-4">{{ key }}</div>
              <div class="col-md-8">
                <span class="float-right badge-secondary break">{{ entry.properties[key] }}</span>
              </div>
            </div>
          </td>
        </tr>
        </tbody>
      </table>
      <div v-for="key in keys(allConfiguration)" :key="key">
        <h4>
          <span>{{ key }}</span>
        </h4>
        <table class="table table-sm table-striped table-bordered table-responsive d-table"
               aria-describedby="Properties">
          <thead>
          <tr>
            <th class="w-40" scope="col">Property</th>
            <th class="w-60" scope="col">Value</th>
          </tr>
          </thead>
          <tbody>
          <tr v-for="item of allConfiguration[key]" :key="item.key">
            <td class="break">{{ item.key }}</td>
            <td class="break">
              <span class="float-right badge-secondary break">{{ item.val }}</span>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./configuration.component.ts"></script>
